### ISSUE TITLE
Generated svg is missing style attribute

### ISSUE THREAD

**Issue by tamzinblake** [svgstore/broccoli-svgstore#17]
Until recently, my generated SVGs had `style="display:none"` appended, and a recent npm update caused that to stop happening. I don't see any obvious way to configure that either. I'm using broccoli-svgstore via ember-cli-svgstore but I suspect the change happened here?

Possibly related: https://github.com/salsify/ember-cli-svgstore/issues/9 and https://github.com/svgstore/svgstore/issues/8

**Comment by BrianSipple** [comment]
Hi Thom,

Thanks for reporting this! It seems that a bit of an oversight has occurred in the process of [handing off `broccoli-svgstore`’s conversion logic to `svgstore`](https://github.com/svgstore/broccoli-svgstore/pull/13). Before, `style: none;` was being [applied manually by `broccoli-svgstore`](https://github.com/svgstore/broccoli-svgstore/blob/fc736ad1f586fca92aa68ee78121540af5004312/index.js#L36), but now, we’re handling attribute configuration as a process of [passing a configuration options to `svgstore`](https://github.com/svgstore/broccoli-svgstore#options).

One thing I failed to catch, however, is that the root `<svg>`'s `style` attribute is not among them. So there’s our issue.

To address this, we’ve been developing a robust API in `svgstore` for configuring attributes on both the root `<svg>` and its child `<symbol>` elements. (See svgstore/svgstore#13 and svgstore/svgstore#15).

These changes will require a major version bump in `svgstore` since it breaks the current API, but I plan on cutting it as soon as svgstore/svgstore#15 gets resolved and updating `broccoli-svgstore` accordingly. Needless to say, I'll keep everyone [watching this issue](https://github.com/salsify/ember-cli-svgstore/issues/9) in the loop (cc @dfreeman). 

Apologies for not being more careful here in the meantime.

**Comment by tamzinblake** [comment]
Cool, our workaround right now involves adding a style attribute right
before appending to the dom, so not high priority for us.
