### ISSUE TITLE
ember-cli-svgstore could not run

### ISSUE THREAD

**Issue by chenxiwei** [svgstore/broccoli-svgstore#30]
![image](https://cloud.githubusercontent.com/assets/3908001/24135908/56683e92-0e47-11e7-8eeb-fe9c33093325.png)
I want to use ember-cli-svgstore in my app.So I download the ember-cli-svgstore from the github,
and after (bower install &npm install),
execute command:ember server.Then It throw errors.
 ember-cli-svgstore depends on broccoli-svgstore.From the errors,I thought maybe it`s a blocked bug on 
  broccoli-svgstore.
development environment:windows 7 (x64)
   node v6.9.1
  ember:2.10.0

**Comment by chenxiwei** [comment]
I found the reason. The line of code below is not useful.
![image](https://cloud.githubusercontent.com/assets/3908001/24141341/211e3176-0e5e-11e7-9b41-4a5f933cd76d.png)

**Comment by lancedikson** [comment]
Ran into the same issue. Is it really necessary? @BrianSipple @jmarquis

**Comment by BrianSipple** [comment]
@chenxiwei @lancedikson @timmorey Thank you all for catching this (I just joined the club myself, coincidentally).

The short backstory is that I added that comment after initially picking up the project and refactoring things in several places. I was skeptical of the line's need, but didn't realize it was broken on Windows, so I let it go.

And so here we are 😄. After looking into it a bit more, I don't think the line is needed at all since `this.outputPath`'s absoluteness is an [inherent part of the Broccoli build step](https://github.com/broccolijs/broccoli-plugin#pluginprototypebuild). I'll remove it and release a patch soon.
